title: "<span style='color: #016b5d;'>Yana Gilichinskaya</span>" # Styling the title with teal color
logo: "/images/logo.jpg?raw=true"
description: |
  <br>
  <span style='font-weight: bold; color: darkgray;'>Data Scientist</span>PhD in Speech-Hearing-Language Sciences. 10+ years in the marketing field. Expertise in SQL, Python, story-telling.
  <br><br>
  <span style='font-weight: bold; color: darkgray;'>Python:</span> NumPy, Pandas, Matplotlib, Seaborn, Scikit-learn, NLP tools, Recommender Systems<br>
  <span style='font-weight: bold; color: darkgray;'>Data Visualization:</span> Amazon Quicksight, Tableau<br> <br>
  <a href="https://www.linkedin.com/in/yana-gilichinskaya/">View My LinkedIn Profile</a><br>
  <a href="pdf/DataScientistFeb24_Yana Gilichinskaya.pdf">My CV</a><br>
  <a target="_blank" href="mailto:yanagil@gmail.com"><i>E-mail</i> me</a>
  <br>
  <!--<a href="https://www.linkedin.com/in/yana-gilichinskaya/">About Me</a><br>-->
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
