title: Yana Gilichinskaya # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks) 
  <br>
  <b>Data Analyst</b> with 10+ years of SQL-based reporting. Experienced Data Dashboard buildier.
  <br><br>
  <b>Python:</b> NumPy, Pandas, Matplotlib, Seaborn, Scikit-learn, NLP tools<br>
  <b>Data Vizualization:</b> Amazon Quicksight, Tableau<br> <br>
  <a href="https://www.linkedin.com/in/yana-gilichinskaya/">View My LinkedIn Profile</a>
  <br>
  <a href="https://www.linkedin.com/in/yana-gilichinskaya/">About Me</a><br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

